Merged gplayers to tmdbplayers
a4k-openproject/json.openplayers pull request #106
Opened 2024-04-06 22:06 UTC by Goldenfreddy0703

Hey there, a couple of weeks ago, GPlayers experienced some downtime. Consequently, I made the decision to integrate its players with TMDBPlayers. I successfully incorporated all the new players and also performed updates on several existing ones. While adding new players was straightforward, updating proved to be a bit challenging, mainly due to the comparison process. Nevertheless, I believe everything should now be accurate. If you like, feel free to merge this PR. If you notice anything wrong, please don't hesitate to message, and I'll do my best to fix it.

Thank you

✨ - Added 9lives Players
✨ - Added Absolution Players
✨ - Added Adina Players
✨ - Added Affenity Players
✨ - Added Amazon Players
✨ - Added Base19 Players
✨ - Added Buds Players
✨ - Added Coalition. Players
✨ - Added Dramacool Players
✨ - Added Dradis Players
✨ - Added Dynasty Players
✨ - Added Fen Players
✨ - Added Fenlight Players
✨ - Added Gaia Players
✨ - Added Hulu Players
✨ - Added Imdbtrailers Players
✨ - Added Kingpin Players
✨ - Added Kit Players
✨ - Added Luffy Players
✨ - Added Metv Players
✨ - Added Moria Players
✨ - Added Netflix Players
✨ - Added Pov Players
✨ - Added Quicksilver Players
✨ - Added Shazam Players
✨ - Added Thechains Players
✨ - Added Thelab Players
✨ - Added Thelabjr Players
✨ - Added Thepromise Players
✨ - Added Twilight Players
✨ - Added Unleashed Players
✨ - Added Wizz Players
✨ - Added Wutu Players
✨ - Added Youtube Players
✨ - Added Zoro Players
⚙️ - Updated Alvin Players
⚙️ - Updated Gaia Players
⚙️ - Updated Genocide Players
⚙️ - Updated Homelander Players
⚙️ - Updated Nightwing Players
⚙️ - Updated Scrubsv2 Players
⚙️ - Updated Thecrew Players

2024-04-06 23:33 UTC, drinfernoo requested changes
Besides the fact that many of these seem to be basically the same addon (just based off of URL structure), there are a number of files that simply don't belong here, have duplicated players which already exist, or have made questionable changes.

2024-04-06 23:33 UTC, drinfernoo commented on amazon.json
This file is the same as [the one included with TMDBHelper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/nexus/resources/players/amazon.json), so it shouldn't be here.

2024-04-06 23:33 UTC, drinfernoo commented on hulu.json
This file is the same as [the one included with TMDBHelper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/nexus/resources/players/hulu.json), so it shouldn't be here.

2024-04-06 23:33 UTC, drinfernoo commented on imdbtrailers.json
This file is the same as [the one included with TMDBHelper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/nexus/resources/players/imdbtrailers.json), so it shouldn't be here.

2024-04-06 23:33 UTC, drinfernoo commented on netflix.json
This file is the same as [the one included with TMDBHelper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/nexus/resources/players/netflix.json), so it shouldn't be here.

2024-04-06 23:33 UTC, drinfernoo commented on youtube.json
This file is the same as [the one included with TMDBHelper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/nexus/resources/players/youtube.json), so it shouldn't be here.

2024-04-06 23:33 UTC, drinfernoo commented on coalition.auto..json
This file has an extra `.` in the filename. I'm not sure if that will work.

2024-04-06 23:33 UTC, drinfernoo commented on direct.genocide.json
> +    "plugin" : "plugin.video.chainsgenocide",
Is this the same addon?

2024-04-06 23:33 UTC, drinfernoo commented on fen.select.json
This is the same as [the one already included in this package](https://github.com/a4k-openproject/json.openplayers/blob/tmdbhelper/direct.fen.select.json), so it shouldn't be here.

2024-04-06 23:33 UTC, drinfernoo commented on fen.auto.json
This file is the same as [the one already included in this package](https://github.com/a4k-openproject/json.openplayers/blob/tmdbhelper/direct.fen.json), except for the name. If it's imperative that the name be changed (though it seems like just `Fen` would be enough), change it in the existing file and remove this one.

2024-04-06 23:33 UTC, drinfernoo commented on direct.alvin.json
> +    "priority" : 300,
Why is this priority being changed?

2024-04-06 23:33 UTC, drinfernoo commented on direct.alvin.json
> +    "is_resolvable" : "true",
Does this addon now support resolvable links?

2024-04-06 23:33 UTC, drinfernoo commented on direct.homelander.json
> +    "is_resolvable" : "true",
Does this addon now support resolvable links?

2024-04-06 23:33 UTC, drinfernoo commented on direct.thecrew.json
> +    "is_resolvable" : "true",
Does this addon now support resolvable links?

2024-04-06 23:33 UTC, drinfernoo commented on direct.scrubsv2.json
> +  "is_resolvable" : "true",
Does this addon now support resolvable links?

2024-04-06 23:33 UTC, drinfernoo commented on direct.scrubsv2.json
> +  "name" : "Scrubs V2",
I see that in this case (also for [THE CREW](https://github.com/a4k-openproject/json.openplayers/pull/106/files#diff-16ab15b0d89507f439acf5f99461ad54921f6e32e369ace3a4e61762fab9be74R2) and [Genocide](https://github.com/a4k-openproject/json.openplayers/pull/106/files#diff-bcee13fb05839d2639477beb372fdc314913677d76d4d0682ef0e903d1d821baR2)) you've removed the color, but decided to leave it in on a few others, and even fix it in Genocide... Is there any logic to these?

2024-04-06 23:33 UTC, drinfernoo commented on direct.thecrew.json
> +    "priority" : 100,
Why is this priority being changed?

2024-04-06 23:33 UTC, drinfernoo commented on kingpin.auto.json
This player is the same as [the one already included in this package](https://github.com/a4k-openproject/json.openplayers/blob/tmdbhelper/kingpin.json), so it shouldn't be here.

2024-04-06 23:33 UTC, drinfernoo commented on nightwing.json
> +    "is_resolvable" : "true",
Does this addon now support resolvable links?

2024-04-06 23:33 UTC, drinfernoo commented on search.dramacool.json
> +   "search_movie"     : [
The formatting in this one is awfully unconventional 🤔

2024-04-06 23:33 UTC, drinfernoo commented on wutu.select.json
> +    "name" : "[COLOR snow]wutu[/COLOR] (Source Select)",
Why is this one colored, when the rest of the players for Wutu are not?

2024-04-06 23:50 UTC, Goldenfreddy0703 commented
Your right, for now, I'm going to work on this more and see what needs to be added and what needs to be modified and everything. Thank you for reviewing these.

2024-04-07 01:58 UTC, Goldenfreddy0703 commented
Hey so im actually going to close this for now and work on this for a later date, reason why is cause i worked on this pr today on my laptop and i should have done this on my desktop. Will have this reopened when finished. Thank you

2024-04-07 17:00 UTC, drinfernoo commented
No need to close this one; you can just make the modifications as a new commit and they'll show up here.

2025-09-23 20:39 UTC, Goldenfreddy0703 commented
Hey so im actually gonna close this cause im going to be making another pr in the future and do a better job merging these soon. Im going to make another pr in the next few min that's going to contain my updated Otaku Players. 

Thanks

2025-09-23 20:39 UTC, closed without merging